'use strict';
// Auto-generated by shallow-doc-parser.test.cjs. DO NOT edit by hand; the
// surface is defined to mirror lib/core/navigation.cjs as Phase 115-02
// expects to consume it (sessionId/nodeId/setBy form for setFocus,
// sessionId/eventType/payload form for recordMemoryEvent).
const calls = { setFocus: [], memoryEvents: [], getActiveFocus: [] };
function reset() { calls.setFocus.length = 0; calls.memoryEvents.length = 0; calls.getActiveFocus.length = 0; }
module.exports = {
  setFocus: function (sid, nid, sb) { calls.setFocus.push({ sid: sid, nid: nid, sb: sb }); return { ok: true, eventId: 'stub-evt-' + calls.setFocus.length }; },
  recordMemoryEvent: function (sid, type, payload) { calls.memoryEvents.push({ sid: sid, type: type, payload: payload }); return { ok: true, eventId: 'stub-mem-' + calls.memoryEvents.length }; },
  getActiveFocus: function (sid) { calls.getActiveFocus.push({ sid: sid }); return null; },
  __calls: calls,
  __reset: reset,
};
